/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Serializer,
  array,
  string,
  struct,
} from '@metaplex-foundation/umi/serializers';

/** Token22 Metadata Extension compatible Metadata format */
export type Metadata = {
  name: string;
  symbol: string;
  uri: string;
  /** Additional metadata for Token22 Metadata Extension compatible Metadata format */
  additionalMetadata: Array<{ label: string; value: string }>;
};

export type MetadataArgs = Metadata;

export function getMetadataSerializer(): Serializer<MetadataArgs, Metadata> {
  return struct<Metadata>(
    [
      ['name', string()],
      ['symbol', string()],
      ['uri', string()],
      [
        'additionalMetadata',
        array(
          struct<any>([
            ['label', string()],
            ['value', string()],
          ])
        ),
      ],
    ],
    { description: 'Metadata' }
  ) as Serializer<MetadataArgs, Metadata>;
}
