/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type BurnTokenizedRecordInstructionAccounts = {
  /** Record owner or class authority for permissioned classes */
  authority: Signer;
  /** Mint account for the tokenized record */
  mint: PublicKey | Pda;
  /** Token Account for the tokenized record */
  tokenAccount: PublicKey | Pda;
  /** Record account associated with the tokenized record */
  record: PublicKey | Pda;
  /** Token2022 Program used to burn the tokenized record */
  token2022?: PublicKey | Pda;
  /** Class account of the record */
  class?: PublicKey | Pda;
};

// Data.
export type BurnTokenizedRecordInstructionData = { discriminator: number };

export type BurnTokenizedRecordInstructionDataArgs = {};

export function getBurnTokenizedRecordInstructionDataSerializer(): Serializer<
  BurnTokenizedRecordInstructionDataArgs,
  BurnTokenizedRecordInstructionData
> {
  return mapSerializer<
    BurnTokenizedRecordInstructionDataArgs,
    any,
    BurnTokenizedRecordInstructionData
  >(
    struct<BurnTokenizedRecordInstructionData>([['discriminator', u8()]], {
      description: 'BurnTokenizedRecordInstructionData',
    }),
    (value) => ({ ...value, discriminator: 11 })
  ) as Serializer<
    BurnTokenizedRecordInstructionDataArgs,
    BurnTokenizedRecordInstructionData
  >;
}

// Instruction.
export function burnTokenizedRecord(
  context: Pick<Context, 'programs'>,
  input: BurnTokenizedRecordInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    mint: { index: 1, isWritable: true as boolean, value: input.mint ?? null },
    tokenAccount: {
      index: 2,
      isWritable: true as boolean,
      value: input.tokenAccount ?? null,
    },
    record: {
      index: 3,
      isWritable: true as boolean,
      value: input.record ?? null,
    },
    token2022: {
      index: 4,
      isWritable: false as boolean,
      value: input.token2022 ?? null,
    },
    class: {
      index: 5,
      isWritable: false as boolean,
      value: input.class ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Default values.
  if (!resolvedAccounts.token2022.value) {
    resolvedAccounts.token2022.value = context.programs.getPublicKey(
      'token2022',
      'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb'
    );
    resolvedAccounts.token2022.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getBurnTokenizedRecordInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
