/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CREATE_RECORD_DISCRIMINATOR = 3;

export function getCreateRecordDiscriminatorBytes() {
  return getU8Encoder().encode(CREATE_RECORD_DISCRIMINATOR);
}

export type CreateRecordInstruction<
  TProgram extends string = typeof SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountClass extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountClass extends string
        ? WritableAccount<TAccountClass>
        : TAccountClass,
      ...TRemainingAccounts,
    ]
  >;

export type CreateRecordInstructionData = {
  discriminator: number;
  expiration: bigint;
  name: string;
  metadata: string;
};

export type CreateRecordInstructionDataArgs = {
  expiration: number | bigint;
  name: string;
  metadata: string;
};

export function getCreateRecordInstructionDataEncoder(): Encoder<CreateRecordInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['expiration', getI64Encoder()],
      ['name', addEncoderSizePrefix(getUtf8Encoder(), getU8Encoder())],
      ['metadata', getUtf8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: 3 })
  );
}

export function getCreateRecordInstructionDataDecoder(): Decoder<CreateRecordInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['expiration', getI64Decoder()],
    ['name', addDecoderSizePrefix(getUtf8Decoder(), getU8Decoder())],
    ['metadata', getUtf8Decoder()],
  ]);
}

export function getCreateRecordInstructionDataCodec(): Codec<
  CreateRecordInstructionDataArgs,
  CreateRecordInstructionData
> {
  return combineCodec(
    getCreateRecordInstructionDataEncoder(),
    getCreateRecordInstructionDataDecoder()
  );
}

export type CreateRecordInput<
  TAccountAuthority extends string = string,
  TAccountClass extends string = string,
> = {
  /** Authority used to freeze/thaw a class */
  authority: TransactionSigner<TAccountAuthority>;
  /** Class account to be frozen/thawed */
  class: Address<TAccountClass>;
  expiration: CreateRecordInstructionDataArgs['expiration'];
  name: CreateRecordInstructionDataArgs['name'];
  metadata: CreateRecordInstructionDataArgs['metadata'];
};

export function getCreateRecordInstruction<
  TAccountAuthority extends string,
  TAccountClass extends string,
  TProgramAddress extends
    Address = typeof SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS,
>(
  input: CreateRecordInput<TAccountAuthority, TAccountClass>,
  config?: { programAddress?: TProgramAddress }
): CreateRecordInstruction<TProgramAddress, TAccountAuthority, TAccountClass> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    class: { value: input.class ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.class),
    ],
    programAddress,
    data: getCreateRecordInstructionDataEncoder().encode(
      args as CreateRecordInstructionDataArgs
    ),
  } as CreateRecordInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountClass
  >;

  return instruction;
}

export type ParsedCreateRecordInstruction<
  TProgram extends string = typeof SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Authority used to freeze/thaw a class */
    authority: TAccountMetas[0];
    /** Class account to be frozen/thawed */
    class: TAccountMetas[1];
  };
  data: CreateRecordInstructionData;
};

export function parseCreateRecordInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedCreateRecordInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      class: getNextAccount(),
    },
    data: getCreateRecordInstructionDataDecoder().decode(instruction.data),
  };
}
