/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bool,
  mapSerializer,
  string,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type CreateClassInstructionAccounts = {
  /** Authority used to create a new class */
  authority: Signer;
  /** New class account to be initialized */
  class: PublicKey | Pda;
  /** System Program used to open our new class account */
  systemProgram?: PublicKey | Pda;
};

// Data.
export type CreateClassInstructionData = {
  discriminator: number;
  isPermissioned: boolean;
  isFrozen: boolean;
  name: string;
  metadata: string;
};

export type CreateClassInstructionDataArgs = {
  isPermissioned: boolean;
  isFrozen: boolean;
  name: string;
  metadata: string;
};

export function getCreateClassInstructionDataSerializer(): Serializer<
  CreateClassInstructionDataArgs,
  CreateClassInstructionData
> {
  return mapSerializer<
    CreateClassInstructionDataArgs,
    any,
    CreateClassInstructionData
  >(
    struct<CreateClassInstructionData>(
      [
        ['discriminator', u8()],
        ['isPermissioned', bool()],
        ['isFrozen', bool()],
        ['name', string({ size: u8() })],
        ['metadata', string({ size: 'variable' })],
      ],
      { description: 'CreateClassInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 0 })
  ) as Serializer<CreateClassInstructionDataArgs, CreateClassInstructionData>;
}

// Args.
export type CreateClassInstructionArgs = CreateClassInstructionDataArgs;

// Instruction.
export function createClass(
  context: Pick<Context, 'programs'>,
  input: CreateClassInstructionAccounts & CreateClassInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    class: {
      index: 1,
      isWritable: true as boolean,
      value: input.class ?? null,
    },
    systemProgram: {
      index: 2,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: CreateClassInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getCreateClassInstructionDataSerializer().serialize(
    resolvedArgs as CreateClassInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
