/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type DeleteRecordAuthorityDelegateInstructionAccounts = {
  /** Authority used to create a delegate */
  authority: Signer;
  /** Record account to create delegate for */
  record: PublicKey | Pda;
  /** Delegate for record account */
  delegate: PublicKey | Pda;
};

// Data.
export type DeleteRecordAuthorityDelegateInstructionData = {
  discriminator: number;
};

export type DeleteRecordAuthorityDelegateInstructionDataArgs = {};

export function getDeleteRecordAuthorityDelegateInstructionDataSerializer(): Serializer<
  DeleteRecordAuthorityDelegateInstructionDataArgs,
  DeleteRecordAuthorityDelegateInstructionData
> {
  return mapSerializer<
    DeleteRecordAuthorityDelegateInstructionDataArgs,
    any,
    DeleteRecordAuthorityDelegateInstructionData
  >(
    struct<DeleteRecordAuthorityDelegateInstructionData>(
      [['discriminator', u8()]],
      { description: 'DeleteRecordAuthorityDelegateInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 10 })
  ) as Serializer<
    DeleteRecordAuthorityDelegateInstructionDataArgs,
    DeleteRecordAuthorityDelegateInstructionData
  >;
}

// Instruction.
export function deleteRecordAuthorityDelegate(
  context: Pick<Context, 'programs'>,
  input: DeleteRecordAuthorityDelegateInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    record: {
      index: 1,
      isWritable: false as boolean,
      value: input.record ?? null,
    },
    delegate: {
      index: 2,
      isWritable: true as boolean,
      value: input.delegate ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getDeleteRecordAuthorityDelegateInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
