/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type DeleteRecordInstructionAccounts = {
  /** Authority used to update a record */
  authority: Signer;
  /** Record account to be updated */
  record: PublicKey | Pda;
  /** Delegate signer for record account */
  delegate?: Signer;
};

// Data.
export type DeleteRecordInstructionData = { discriminator: number };

export type DeleteRecordInstructionDataArgs = {};

export function getDeleteRecordInstructionDataSerializer(): Serializer<
  DeleteRecordInstructionDataArgs,
  DeleteRecordInstructionData
> {
  return mapSerializer<
    DeleteRecordInstructionDataArgs,
    any,
    DeleteRecordInstructionData
  >(
    struct<DeleteRecordInstructionData>([['discriminator', u8()]], {
      description: 'DeleteRecordInstructionData',
    }),
    (value) => ({ ...value, discriminator: 6 })
  ) as Serializer<DeleteRecordInstructionDataArgs, DeleteRecordInstructionData>;
}

// Instruction.
export function deleteRecord(
  context: Pick<Context, 'programs'>,
  input: DeleteRecordInstructionAccounts
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    record: {
      index: 1,
      isWritable: true as boolean,
      value: input.record ?? null,
    },
    delegate: {
      index: 2,
      isWritable: false as boolean,
      value: input.delegate ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getDeleteRecordInstructionDataSerializer().serialize({});

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
