/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bool,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type FreezeRecordInstructionAccounts = {
  /** Record owner or class authority for permissioned classes */
  authority: Signer;
  /** Record account to be updated */
  record: PublicKey | Pda;
  /** Class account of the record */
  class: PublicKey | Pda;
};

// Data.
export type FreezeRecordInstructionData = {
  discriminator: number;
  isFrozen: boolean;
};

export type FreezeRecordInstructionDataArgs = { isFrozen: boolean };

export function getFreezeRecordInstructionDataSerializer(): Serializer<
  FreezeRecordInstructionDataArgs,
  FreezeRecordInstructionData
> {
  return mapSerializer<
    FreezeRecordInstructionDataArgs,
    any,
    FreezeRecordInstructionData
  >(
    struct<FreezeRecordInstructionData>(
      [
        ['discriminator', u8()],
        ['isFrozen', bool()],
      ],
      { description: 'FreezeRecordInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 9 })
  ) as Serializer<FreezeRecordInstructionDataArgs, FreezeRecordInstructionData>;
}

// Args.
export type FreezeRecordInstructionArgs = FreezeRecordInstructionDataArgs;

// Instruction.
export function freezeRecord(
  context: Pick<Context, 'programs'>,
  input: FreezeRecordInstructionAccounts & FreezeRecordInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsWjm76StJucL7atFyPSdXFaVLNPFqEt1uFEDPrZsn'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    record: {
      index: 1,
      isWritable: true as boolean,
      value: input.record ?? null,
    },
    class: {
      index: 2,
      isWritable: false as boolean,
      value: input.class ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: FreezeRecordInstructionArgs = { ...input };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getFreezeRecordInstructionDataSerializer().serialize(
    resolvedArgs as FreezeRecordInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
