/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bool,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type FreezeClassInstructionAccounts = {
  /** Authority used to freeze/thaw a class */
  authority: Signer;
  /** Class account to be frozen/thawed */
  class: PublicKey | Pda;
};

// Data.
export type FreezeClassInstructionData = {
  discriminator: number;
  isFrozen: boolean;
};

export type FreezeClassInstructionDataArgs = { isFrozen: boolean };

export function getFreezeClassInstructionDataSerializer(): Serializer<
  FreezeClassInstructionDataArgs,
  FreezeClassInstructionData
> {
  return mapSerializer<
    FreezeClassInstructionDataArgs,
    any,
    FreezeClassInstructionData
  >(
    struct<FreezeClassInstructionData>(
      [
        ['discriminator', u8()],
        ['isFrozen', bool()],
      ],
      { description: 'FreezeClassInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 2 })
  ) as Serializer<FreezeClassInstructionDataArgs, FreezeClassInstructionData>;
}

// Args.
export type FreezeClassInstructionArgs = FreezeClassInstructionDataArgs;

// Instruction.
export function freezeClass(
  context: Pick<Context, 'programs'>,
  input: FreezeClassInstructionAccounts & FreezeClassInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    class: {
      index: 1,
      isWritable: true as boolean,
      value: input.class ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: FreezeClassInstructionArgs = { ...input };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getFreezeClassInstructionDataSerializer().serialize(
    resolvedArgs as FreezeClassInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
