/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_CLASS_FROZEN_DISCRIMINATOR = 2;

export function getUpdateClassFrozenDiscriminatorBytes() {
  return getU8Encoder().encode(UPDATE_CLASS_FROZEN_DISCRIMINATOR);
}

export type UpdateClassFrozenInstruction<
  TProgram extends string = typeof SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountClass extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountClass extends string
        ? WritableAccount<TAccountClass>
        : TAccountClass,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateClassFrozenInstructionData = {
  discriminator: number;
  isFrozen: boolean;
};

export type UpdateClassFrozenInstructionDataArgs = { isFrozen: boolean };

export function getUpdateClassFrozenInstructionDataEncoder(): Encoder<UpdateClassFrozenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['isFrozen', getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: 2 })
  );
}

export function getUpdateClassFrozenInstructionDataDecoder(): Decoder<UpdateClassFrozenInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['isFrozen', getBooleanDecoder()],
  ]);
}

export function getUpdateClassFrozenInstructionDataCodec(): Codec<
  UpdateClassFrozenInstructionDataArgs,
  UpdateClassFrozenInstructionData
> {
  return combineCodec(
    getUpdateClassFrozenInstructionDataEncoder(),
    getUpdateClassFrozenInstructionDataDecoder()
  );
}

export type UpdateClassFrozenInput<
  TAccountAuthority extends string = string,
  TAccountClass extends string = string,
> = {
  /** Authority used to freeze/thaw a class */
  authority: TransactionSigner<TAccountAuthority>;
  /** Class account to be frozen/thawed */
  class: Address<TAccountClass>;
  isFrozen: UpdateClassFrozenInstructionDataArgs['isFrozen'];
};

export function getUpdateClassFrozenInstruction<
  TAccountAuthority extends string,
  TAccountClass extends string,
  TProgramAddress extends
    Address = typeof SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS,
>(
  input: UpdateClassFrozenInput<TAccountAuthority, TAccountClass>,
  config?: { programAddress?: TProgramAddress }
): UpdateClassFrozenInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountClass
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    class: { value: input.class ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.class),
    ],
    programAddress,
    data: getUpdateClassFrozenInstructionDataEncoder().encode(
      args as UpdateClassFrozenInstructionDataArgs
    ),
  } as UpdateClassFrozenInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountClass
  >;

  return instruction;
}

export type ParsedUpdateClassFrozenInstruction<
  TProgram extends string = typeof SOLANA_RECORD_SERVICE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Authority used to freeze/thaw a class */
    authority: TAccountMetas[0];
    /** Class account to be frozen/thawed */
    class: TAccountMetas[1];
  };
  data: UpdateClassFrozenInstructionData;
};

export function parseUpdateClassFrozenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedUpdateClassFrozenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      class: getNextAccount(),
    },
    data: getUpdateClassFrozenInstructionDataDecoder().decode(instruction.data),
  };
}
