/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  i64,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type UpdateRecordExpiryInstructionAccounts = {
  /** Record owner or class authority for permissioned classes */
  authority: Signer;
  /** Account that will pay of get refunded for the record update */
  payer: Signer;
  /** Record account to be updated */
  record: PublicKey | Pda;
  /** Class account of the record */
  class: PublicKey | Pda;
  /** System Program used to extend our record account */
  systemProgram?: PublicKey | Pda;
};

// Data.
export type UpdateRecordExpiryInstructionData = {
  discriminator: number;
  expiry: bigint;
};

export type UpdateRecordExpiryInstructionDataArgs = { expiry: number | bigint };

export function getUpdateRecordExpiryInstructionDataSerializer(): Serializer<
  UpdateRecordExpiryInstructionDataArgs,
  UpdateRecordExpiryInstructionData
> {
  return mapSerializer<
    UpdateRecordExpiryInstructionDataArgs,
    any,
    UpdateRecordExpiryInstructionData
  >(
    struct<UpdateRecordExpiryInstructionData>(
      [
        ['discriminator', u8()],
        ['expiry', i64()],
      ],
      { description: 'UpdateRecordExpiryInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 6 })
  ) as Serializer<
    UpdateRecordExpiryInstructionDataArgs,
    UpdateRecordExpiryInstructionData
  >;
}

// Args.
export type UpdateRecordExpiryInstructionArgs =
  UpdateRecordExpiryInstructionDataArgs;

// Instruction.
export function updateRecordExpiry(
  context: Pick<Context, 'programs'>,
  input: UpdateRecordExpiryInstructionAccounts &
    UpdateRecordExpiryInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsWjm76StJucL7atFyPSdXFaVLNPFqEt1uFEDPrZsn'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    payer: {
      index: 1,
      isWritable: true as boolean,
      value: input.payer ?? null,
    },
    record: {
      index: 2,
      isWritable: true as boolean,
      value: input.record ?? null,
    },
    class: {
      index: 3,
      isWritable: false as boolean,
      value: input.class ?? null,
    },
    systemProgram: {
      index: 4,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: UpdateRecordExpiryInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getUpdateRecordExpiryInstructionDataSerializer().serialize(
    resolvedArgs as UpdateRecordExpiryInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
