/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  bytes,
  mapSerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type UpdateRecordInstructionAccounts = {
  /** Record owner or class authority for permissioned classes */
  authority: Signer;
  /** Account that will pay of get refunded for the record update */
  payer: Signer;
  /** Record account to be updated */
  record: PublicKey | Pda;
  /** System Program used to extend our record account */
  systemProgram?: PublicKey | Pda;
  /** Class account of the record */
  class?: PublicKey | Pda;
};

// Data.
export type UpdateRecordInstructionData = {
  discriminator: number;
  data: Uint8Array;
};

export type UpdateRecordInstructionDataArgs = { data: Uint8Array };

export function getUpdateRecordInstructionDataSerializer(): Serializer<
  UpdateRecordInstructionDataArgs,
  UpdateRecordInstructionData
> {
  return mapSerializer<
    UpdateRecordInstructionDataArgs,
    any,
    UpdateRecordInstructionData
  >(
    struct<UpdateRecordInstructionData>(
      [
        ['discriminator', u8()],
        ['data', bytes()],
      ],
      { description: 'UpdateRecordInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 4 })
  ) as Serializer<UpdateRecordInstructionDataArgs, UpdateRecordInstructionData>;
}

// Args.
export type UpdateRecordInstructionArgs = UpdateRecordInstructionDataArgs;

// Instruction.
export function updateRecord(
  context: Pick<Context, 'programs'>,
  input: UpdateRecordInstructionAccounts & UpdateRecordInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    payer: {
      index: 1,
      isWritable: true as boolean,
      value: input.payer ?? null,
    },
    record: {
      index: 2,
      isWritable: true as boolean,
      value: input.record ?? null,
    },
    systemProgram: {
      index: 3,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
    class: {
      index: 4,
      isWritable: false as boolean,
      value: input.class ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: UpdateRecordInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getUpdateRecordInstructionDataSerializer().serialize(
    resolvedArgs as UpdateRecordInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
