/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  mapSerializer,
  publicKey as publicKeySerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type UpdateClassAuthorityInstructionAccounts = {
  /** Authority used to update a class */
  authority: Signer;
  /** Account that will pay of get refunded for the class update */
  payer: Signer;
  /** Class account to be updated */
  class: PublicKey | Pda;
  /** System Program used to extend our class account */
  systemProgram?: PublicKey | Pda;
};

// Data.
export type UpdateClassAuthorityInstructionData = {
  discriminator: number;
  newAuthority: PublicKey;
};

export type UpdateClassAuthorityInstructionDataArgs = {
  newAuthority: PublicKey;
};

export function getUpdateClassAuthorityInstructionDataSerializer(): Serializer<
  UpdateClassAuthorityInstructionDataArgs,
  UpdateClassAuthorityInstructionData
> {
  return mapSerializer<
    UpdateClassAuthorityInstructionDataArgs,
    any,
    UpdateClassAuthorityInstructionData
  >(
    struct<UpdateClassAuthorityInstructionData>(
      [
        ['discriminator', u8()],
        ['newAuthority', publicKeySerializer()],
      ],
      { description: 'UpdateClassAuthorityInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 2 })
  ) as Serializer<
    UpdateClassAuthorityInstructionDataArgs,
    UpdateClassAuthorityInstructionData
  >;
}

// Args.
export type UpdateClassAuthorityInstructionArgs =
  UpdateClassAuthorityInstructionDataArgs;

// Instruction.
export function updateClassAuthority(
  context: Pick<Context, 'programs'>,
  input: UpdateClassAuthorityInstructionAccounts &
    UpdateClassAuthorityInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsWjm76StJucL7atFyPSdXFaVLNPFqEt1uFEDPrZsn'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    payer: {
      index: 1,
      isWritable: true as boolean,
      value: input.payer ?? null,
    },
    class: {
      index: 2,
      isWritable: true as boolean,
      value: input.class ?? null,
    },
    systemProgram: {
      index: 3,
      isWritable: false as boolean,
      value: input.systemProgram ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: UpdateClassAuthorityInstructionArgs = { ...input };

  // Default values.
  if (!resolvedAccounts.systemProgram.value) {
    resolvedAccounts.systemProgram.value = context.programs.getPublicKey(
      'systemProgram',
      '11111111111111111111111111111111'
    );
    resolvedAccounts.systemProgram.isWritable = false;
  }

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data = getUpdateClassAuthorityInstructionDataSerializer().serialize(
    resolvedArgs as UpdateClassAuthorityInstructionDataArgs
  );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
