/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  Context,
  Pda,
  PublicKey,
  Signer,
  TransactionBuilder,
  transactionBuilder,
} from '@metaplex-foundation/umi';
import {
  Serializer,
  mapSerializer,
  publicKey as publicKeySerializer,
  struct,
  u8,
} from '@metaplex-foundation/umi/serializers';
import {
  ResolvedAccount,
  ResolvedAccountsWithIndices,
  getAccountMetasAndSigners,
} from '../shared';

// Accounts.
export type UpdateRecordAuthorityDelegateInstructionAccounts = {
  /** Authority used to create a delegate */
  authority: Signer;
  /** Record account to create delegate for */
  record: PublicKey | Pda;
  /** Delegate for record account */
  delegate: PublicKey | Pda;
};

// Data.
export type UpdateRecordAuthorityDelegateInstructionData = {
  discriminator: number;
  updateAuthority: PublicKey;
  freezeAuthority: PublicKey;
  transferAuthority: PublicKey;
  burnAuthority: PublicKey;
  authorityProgram: PublicKey;
};

export type UpdateRecordAuthorityDelegateInstructionDataArgs = {
  updateAuthority: PublicKey;
  freezeAuthority: PublicKey;
  transferAuthority: PublicKey;
  burnAuthority: PublicKey;
  authorityProgram: PublicKey;
};

export function getUpdateRecordAuthorityDelegateInstructionDataSerializer(): Serializer<
  UpdateRecordAuthorityDelegateInstructionDataArgs,
  UpdateRecordAuthorityDelegateInstructionData
> {
  return mapSerializer<
    UpdateRecordAuthorityDelegateInstructionDataArgs,
    any,
    UpdateRecordAuthorityDelegateInstructionData
  >(
    struct<UpdateRecordAuthorityDelegateInstructionData>(
      [
        ['discriminator', u8()],
        ['updateAuthority', publicKeySerializer()],
        ['freezeAuthority', publicKeySerializer()],
        ['transferAuthority', publicKeySerializer()],
        ['burnAuthority', publicKeySerializer()],
        ['authorityProgram', publicKeySerializer()],
      ],
      { description: 'UpdateRecordAuthorityDelegateInstructionData' }
    ),
    (value) => ({ ...value, discriminator: 9 })
  ) as Serializer<
    UpdateRecordAuthorityDelegateInstructionDataArgs,
    UpdateRecordAuthorityDelegateInstructionData
  >;
}

// Args.
export type UpdateRecordAuthorityDelegateInstructionArgs =
  UpdateRecordAuthorityDelegateInstructionDataArgs;

// Instruction.
export function updateRecordAuthorityDelegate(
  context: Pick<Context, 'programs'>,
  input: UpdateRecordAuthorityDelegateInstructionAccounts &
    UpdateRecordAuthorityDelegateInstructionArgs
): TransactionBuilder {
  // Program ID.
  const programId = context.programs.getPublicKey(
    'solanaRecordService',
    'srsUi2TVUUCyGcZdopxJauk8ZBzgAaHHZCVUhm5ifPa'
  );

  // Accounts.
  const resolvedAccounts = {
    authority: {
      index: 0,
      isWritable: true as boolean,
      value: input.authority ?? null,
    },
    record: {
      index: 1,
      isWritable: true as boolean,
      value: input.record ?? null,
    },
    delegate: {
      index: 2,
      isWritable: true as boolean,
      value: input.delegate ?? null,
    },
  } satisfies ResolvedAccountsWithIndices;

  // Arguments.
  const resolvedArgs: UpdateRecordAuthorityDelegateInstructionArgs = {
    ...input,
  };

  // Accounts in order.
  const orderedAccounts: ResolvedAccount[] = Object.values(
    resolvedAccounts
  ).sort((a, b) => a.index - b.index);

  // Keys and Signers.
  const [keys, signers] = getAccountMetasAndSigners(
    orderedAccounts,
    'programId',
    programId
  );

  // Data.
  const data =
    getUpdateRecordAuthorityDelegateInstructionDataSerializer().serialize(
      resolvedArgs as UpdateRecordAuthorityDelegateInstructionDataArgs
    );

  // Bytes Created On Chain.
  const bytesCreatedOnChain = 0;

  return transactionBuilder([
    { instruction: { keys, programId, data }, signers, bytesCreatedOnChain },
  ]);
}
