//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct DeleteRecordAuthorityDelegate {
    /// Authority used to create a delegate
    pub authority: solana_program::pubkey::Pubkey,
    /// Record account to create delegate for
    pub record: solana_program::pubkey::Pubkey,
    /// Delegate for record account
    pub delegate: solana_program::pubkey::Pubkey,
}

impl DeleteRecordAuthorityDelegate {
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.authority,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.record,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.delegate,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&DeleteRecordAuthorityDelegateInstructionData::new()).unwrap();

        solana_program::instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DeleteRecordAuthorityDelegateInstructionData {
    discriminator: u8,
}

impl DeleteRecordAuthorityDelegateInstructionData {
    pub fn new() -> Self {
        Self { discriminator: 10 }
    }
}

impl Default for DeleteRecordAuthorityDelegateInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `DeleteRecordAuthorityDelegate`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` record
///   2. `[writable]` delegate
#[derive(Clone, Debug, Default)]
pub struct DeleteRecordAuthorityDelegateBuilder {
    authority: Option<solana_program::pubkey::Pubkey>,
    record: Option<solana_program::pubkey::Pubkey>,
    delegate: Option<solana_program::pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl DeleteRecordAuthorityDelegateBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Authority used to create a delegate
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_program::pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Record account to create delegate for
    #[inline(always)]
    pub fn record(&mut self, record: solana_program::pubkey::Pubkey) -> &mut Self {
        self.record = Some(record);
        self
    }
    /// Delegate for record account
    #[inline(always)]
    pub fn delegate(&mut self, delegate: solana_program::pubkey::Pubkey) -> &mut Self {
        self.delegate = Some(delegate);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = DeleteRecordAuthorityDelegate {
            authority: self.authority.expect("authority is not set"),
            record: self.record.expect("record is not set"),
            delegate: self.delegate.expect("delegate is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `delete_record_authority_delegate` CPI accounts.
pub struct DeleteRecordAuthorityDelegateCpiAccounts<'a, 'b> {
    /// Authority used to create a delegate
    pub authority: &'b solana_program::account_info::AccountInfo<'a>,
    /// Record account to create delegate for
    pub record: &'b solana_program::account_info::AccountInfo<'a>,
    /// Delegate for record account
    pub delegate: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `delete_record_authority_delegate` CPI instruction.
pub struct DeleteRecordAuthorityDelegateCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,
    /// Authority used to create a delegate
    pub authority: &'b solana_program::account_info::AccountInfo<'a>,
    /// Record account to create delegate for
    pub record: &'b solana_program::account_info::AccountInfo<'a>,
    /// Delegate for record account
    pub delegate: &'b solana_program::account_info::AccountInfo<'a>,
}

impl<'a, 'b> DeleteRecordAuthorityDelegateCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: DeleteRecordAuthorityDelegateCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            record: accounts.record,
            delegate: accounts.delegate,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.record.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.delegate.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&DeleteRecordAuthorityDelegateInstructionData::new()).unwrap();

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.record.clone());
        account_infos.push(self.delegate.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `DeleteRecordAuthorityDelegate` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` record
///   2. `[writable]` delegate
#[derive(Clone, Debug)]
pub struct DeleteRecordAuthorityDelegateCpiBuilder<'a, 'b> {
    instruction: Box<DeleteRecordAuthorityDelegateCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> DeleteRecordAuthorityDelegateCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(DeleteRecordAuthorityDelegateCpiBuilderInstruction {
            __program: program,
            authority: None,
            record: None,
            delegate: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Authority used to create a delegate
    #[inline(always)]
    pub fn authority(
        &mut self,
        authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Record account to create delegate for
    #[inline(always)]
    pub fn record(
        &mut self,
        record: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.record = Some(record);
        self
    }
    /// Delegate for record account
    #[inline(always)]
    pub fn delegate(
        &mut self,
        delegate: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.delegate = Some(delegate);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let instruction = DeleteRecordAuthorityDelegateCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            record: self.instruction.record.expect("record is not set"),

            delegate: self.instruction.delegate.expect("delegate is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct DeleteRecordAuthorityDelegateCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    record: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    delegate: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
