//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct FreezeRecord {
    /// Authority used to update a record
    pub authority: solana_program::pubkey::Pubkey,
    /// Record account to be updated
    pub record: solana_program::pubkey::Pubkey,
    /// Delegate signer for record account
    pub delegate: Option<solana_program::pubkey::Pubkey>,
}

impl FreezeRecord {
    pub fn instruction(
        &self,
        args: FreezeRecordInstructionArgs,
    ) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: FreezeRecordInstructionArgs,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.authority,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.record,
            false,
        ));
        if let Some(delegate) = self.delegate {
            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
                delegate, true,
            ));
        } else {
            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
                crate::SOLANA_RECORD_SERVICE_ID,
                false,
            ));
        }
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&FreezeRecordInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_program::instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FreezeRecordInstructionData {
    discriminator: u8,
}

impl FreezeRecordInstructionData {
    pub fn new() -> Self {
        Self { discriminator: 7 }
    }
}

impl Default for FreezeRecordInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FreezeRecordInstructionArgs {
    pub is_frozen: bool,
}

/// Instruction builder for `FreezeRecord`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` record
///   2. `[signer, optional]` delegate
#[derive(Clone, Debug, Default)]
pub struct FreezeRecordBuilder {
    authority: Option<solana_program::pubkey::Pubkey>,
    record: Option<solana_program::pubkey::Pubkey>,
    delegate: Option<solana_program::pubkey::Pubkey>,
    is_frozen: Option<bool>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl FreezeRecordBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Authority used to update a record
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_program::pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Record account to be updated
    #[inline(always)]
    pub fn record(&mut self, record: solana_program::pubkey::Pubkey) -> &mut Self {
        self.record = Some(record);
        self
    }
    /// `[optional account]`
    /// Delegate signer for record account
    #[inline(always)]
    pub fn delegate(&mut self, delegate: Option<solana_program::pubkey::Pubkey>) -> &mut Self {
        self.delegate = delegate;
        self
    }
    #[inline(always)]
    pub fn is_frozen(&mut self, is_frozen: bool) -> &mut Self {
        self.is_frozen = Some(is_frozen);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = FreezeRecord {
            authority: self.authority.expect("authority is not set"),
            record: self.record.expect("record is not set"),
            delegate: self.delegate,
        };
        let args = FreezeRecordInstructionArgs {
            is_frozen: self.is_frozen.clone().expect("is_frozen is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `freeze_record` CPI accounts.
pub struct FreezeRecordCpiAccounts<'a, 'b> {
    /// Authority used to update a record
    pub authority: &'b solana_program::account_info::AccountInfo<'a>,
    /// Record account to be updated
    pub record: &'b solana_program::account_info::AccountInfo<'a>,
    /// Delegate signer for record account
    pub delegate: Option<&'b solana_program::account_info::AccountInfo<'a>>,
}

/// `freeze_record` CPI instruction.
pub struct FreezeRecordCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,
    /// Authority used to update a record
    pub authority: &'b solana_program::account_info::AccountInfo<'a>,
    /// Record account to be updated
    pub record: &'b solana_program::account_info::AccountInfo<'a>,
    /// Delegate signer for record account
    pub delegate: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    /// The arguments for the instruction.
    pub __args: FreezeRecordInstructionArgs,
}

impl<'a, 'b> FreezeRecordCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: FreezeRecordCpiAccounts<'a, 'b>,
        args: FreezeRecordInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            record: accounts.record,
            delegate: accounts.delegate,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.record.key,
            false,
        ));
        if let Some(delegate) = self.delegate {
            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
                *delegate.key,
                true,
            ));
        } else {
            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
                crate::SOLANA_RECORD_SERVICE_ID,
                false,
            ));
        }
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&FreezeRecordInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.record.clone());
        if let Some(delegate) = self.delegate {
            account_infos.push(delegate.clone());
        }
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `FreezeRecord` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` record
///   2. `[signer, optional]` delegate
#[derive(Clone, Debug)]
pub struct FreezeRecordCpiBuilder<'a, 'b> {
    instruction: Box<FreezeRecordCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> FreezeRecordCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(FreezeRecordCpiBuilderInstruction {
            __program: program,
            authority: None,
            record: None,
            delegate: None,
            is_frozen: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Authority used to update a record
    #[inline(always)]
    pub fn authority(
        &mut self,
        authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Record account to be updated
    #[inline(always)]
    pub fn record(
        &mut self,
        record: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.record = Some(record);
        self
    }
    /// `[optional account]`
    /// Delegate signer for record account
    #[inline(always)]
    pub fn delegate(
        &mut self,
        delegate: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.delegate = delegate;
        self
    }
    #[inline(always)]
    pub fn is_frozen(&mut self, is_frozen: bool) -> &mut Self {
        self.instruction.is_frozen = Some(is_frozen);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let args = FreezeRecordInstructionArgs {
            is_frozen: self
                .instruction
                .is_frozen
                .clone()
                .expect("is_frozen is not set"),
        };
        let instruction = FreezeRecordCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            record: self.instruction.record.expect("record is not set"),

            delegate: self.instruction.delegate,
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct FreezeRecordCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    record: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    delegate: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    is_frozen: Option<bool>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
