//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct FreezeClass {
    /// Authority used to freeze/thaw a class
    pub authority: solana_pubkey::Pubkey,
    /// Class account to be frozen/thawed
    pub class: solana_pubkey::Pubkey,
}

impl FreezeClass {
    pub fn instruction(&self, args: FreezeClassInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: FreezeClassInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.authority, true));
        accounts.push(solana_instruction::AccountMeta::new(self.class, false));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&FreezeClassInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FreezeClassInstructionData {
    discriminator: u8,
}

impl FreezeClassInstructionData {
    pub fn new() -> Self {
        Self { discriminator: 2 }
    }
}

impl Default for FreezeClassInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct FreezeClassInstructionArgs {
    pub is_frozen: bool,
}

/// Instruction builder for `FreezeClass`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` class
#[derive(Clone, Debug, Default)]
pub struct FreezeClassBuilder {
    authority: Option<solana_pubkey::Pubkey>,
    class: Option<solana_pubkey::Pubkey>,
    is_frozen: Option<bool>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl FreezeClassBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Authority used to freeze/thaw a class
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Class account to be frozen/thawed
    #[inline(always)]
    pub fn class(&mut self, class: solana_pubkey::Pubkey) -> &mut Self {
        self.class = Some(class);
        self
    }
    #[inline(always)]
    pub fn is_frozen(&mut self, is_frozen: bool) -> &mut Self {
        self.is_frozen = Some(is_frozen);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = FreezeClass {
            authority: self.authority.expect("authority is not set"),
            class: self.class.expect("class is not set"),
        };
        let args = FreezeClassInstructionArgs {
            is_frozen: self.is_frozen.clone().expect("is_frozen is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `freeze_class` CPI accounts.
pub struct FreezeClassCpiAccounts<'a, 'b> {
    /// Authority used to freeze/thaw a class
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Class account to be frozen/thawed
    pub class: &'b solana_account_info::AccountInfo<'a>,
}

/// `freeze_class` CPI instruction.
pub struct FreezeClassCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Authority used to freeze/thaw a class
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Class account to be frozen/thawed
    pub class: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: FreezeClassInstructionArgs,
}

impl<'a, 'b> FreezeClassCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: FreezeClassCpiAccounts<'a, 'b>,
        args: FreezeClassInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            class: accounts.class,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(2 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.class.key, false));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&FreezeClassInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.class.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `FreezeClass` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` class
#[derive(Clone, Debug)]
pub struct FreezeClassCpiBuilder<'a, 'b> {
    instruction: Box<FreezeClassCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> FreezeClassCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(FreezeClassCpiBuilderInstruction {
            __program: program,
            authority: None,
            class: None,
            is_frozen: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Authority used to freeze/thaw a class
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Class account to be frozen/thawed
    #[inline(always)]
    pub fn class(&mut self, class: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.class = Some(class);
        self
    }
    #[inline(always)]
    pub fn is_frozen(&mut self, is_frozen: bool) -> &mut Self {
        self.instruction.is_frozen = Some(is_frozen);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let args = FreezeClassInstructionArgs {
            is_frozen: self
                .instruction
                .is_frozen
                .clone()
                .expect("is_frozen is not set"),
        };
        let instruction = FreezeClassCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            class: self.instruction.class.expect("class is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct FreezeClassCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    class: Option<&'b solana_account_info::AccountInfo<'a>>,
    is_frozen: Option<bool>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
