//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct MintTokenizedRecord {
    /// Record owner
    pub owner: solana_pubkey::Pubkey,
    /// Account that will pay for the mint account
    pub payer: solana_pubkey::Pubkey,
    /// Record owner or class authority for permissioned classes
    pub authority: solana_pubkey::Pubkey,
    /// Record account associated with the tokenized record
    pub record: solana_pubkey::Pubkey,
    /// Mint account for the tokenized record
    pub mint: solana_pubkey::Pubkey,
    /// Class account of the record
    pub class: solana_pubkey::Pubkey,
    /// Group account for the tokenized record
    pub group: solana_pubkey::Pubkey,
    /// Token Account for the tokenized record
    pub token_account: solana_pubkey::Pubkey,
    /// Associated Token Program used to create our token
    pub associated_token_program: solana_pubkey::Pubkey,
    /// Token2022 Program used to create our token
    pub token2022: solana_pubkey::Pubkey,
    /// System Program used to create our token
    pub system_program: solana_pubkey::Pubkey,
}

impl MintTokenizedRecord {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(11 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.owner, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.record, false));
        accounts.push(solana_instruction::AccountMeta::new(self.mint, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.class, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.group, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token2022,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&MintTokenizedRecordInstructionData::new()).unwrap();

        solana_instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MintTokenizedRecordInstructionData {
    discriminator: u8,
}

impl MintTokenizedRecordInstructionData {
    pub fn new() -> Self {
        Self { discriminator: 8 }
    }
}

impl Default for MintTokenizedRecordInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `MintTokenizedRecord`.
///
/// ### Accounts:
///
///   0. `[]` owner
///   1. `[writable, signer]` payer
///   2. `[signer]` authority
///   3. `[writable]` record
///   4. `[writable]` mint
///   5. `[]` class
///   6. `[writable]` group
///   7. `[writable]` token_account
///   8. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
///   9. `[optional]` token2022 (default to `TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb`)
///   10. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct MintTokenizedRecordBuilder {
    owner: Option<solana_pubkey::Pubkey>,
    payer: Option<solana_pubkey::Pubkey>,
    authority: Option<solana_pubkey::Pubkey>,
    record: Option<solana_pubkey::Pubkey>,
    mint: Option<solana_pubkey::Pubkey>,
    class: Option<solana_pubkey::Pubkey>,
    group: Option<solana_pubkey::Pubkey>,
    token_account: Option<solana_pubkey::Pubkey>,
    associated_token_program: Option<solana_pubkey::Pubkey>,
    token2022: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl MintTokenizedRecordBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Record owner
    #[inline(always)]
    pub fn owner(&mut self, owner: solana_pubkey::Pubkey) -> &mut Self {
        self.owner = Some(owner);
        self
    }
    /// Account that will pay for the mint account
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_pubkey::Pubkey) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// Record owner or class authority for permissioned classes
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Record account associated with the tokenized record
    #[inline(always)]
    pub fn record(&mut self, record: solana_pubkey::Pubkey) -> &mut Self {
        self.record = Some(record);
        self
    }
    /// Mint account for the tokenized record
    #[inline(always)]
    pub fn mint(&mut self, mint: solana_pubkey::Pubkey) -> &mut Self {
        self.mint = Some(mint);
        self
    }
    /// Class account of the record
    #[inline(always)]
    pub fn class(&mut self, class: solana_pubkey::Pubkey) -> &mut Self {
        self.class = Some(class);
        self
    }
    /// Group account for the tokenized record
    #[inline(always)]
    pub fn group(&mut self, group: solana_pubkey::Pubkey) -> &mut Self {
        self.group = Some(group);
        self
    }
    /// Token Account for the tokenized record
    #[inline(always)]
    pub fn token_account(&mut self, token_account: solana_pubkey::Pubkey) -> &mut Self {
        self.token_account = Some(token_account);
        self
    }
    /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
    /// Associated Token Program used to create our token
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.associated_token_program = Some(associated_token_program);
        self
    }
    /// `[optional account, default to 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb']`
    /// Token2022 Program used to create our token
    #[inline(always)]
    pub fn token2022(&mut self, token2022: solana_pubkey::Pubkey) -> &mut Self {
        self.token2022 = Some(token2022);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// System Program used to create our token
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = MintTokenizedRecord {
            owner: self.owner.expect("owner is not set"),
            payer: self.payer.expect("payer is not set"),
            authority: self.authority.expect("authority is not set"),
            record: self.record.expect("record is not set"),
            mint: self.mint.expect("mint is not set"),
            class: self.class.expect("class is not set"),
            group: self.group.expect("group is not set"),
            token_account: self.token_account.expect("token_account is not set"),
            associated_token_program: self.associated_token_program.unwrap_or(
                solana_pubkey::pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
            ),
            token2022: self.token2022.unwrap_or(solana_pubkey::pubkey!(
                "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
            )),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `mint_tokenized_record` CPI accounts.
pub struct MintTokenizedRecordCpiAccounts<'a, 'b> {
    /// Record owner
    pub owner: &'b solana_account_info::AccountInfo<'a>,
    /// Account that will pay for the mint account
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Record owner or class authority for permissioned classes
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Record account associated with the tokenized record
    pub record: &'b solana_account_info::AccountInfo<'a>,
    /// Mint account for the tokenized record
    pub mint: &'b solana_account_info::AccountInfo<'a>,
    /// Class account of the record
    pub class: &'b solana_account_info::AccountInfo<'a>,
    /// Group account for the tokenized record
    pub group: &'b solana_account_info::AccountInfo<'a>,
    /// Token Account for the tokenized record
    pub token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Associated Token Program used to create our token
    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token2022 Program used to create our token
    pub token2022: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used to create our token
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `mint_tokenized_record` CPI instruction.
pub struct MintTokenizedRecordCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Record owner
    pub owner: &'b solana_account_info::AccountInfo<'a>,
    /// Account that will pay for the mint account
    pub payer: &'b solana_account_info::AccountInfo<'a>,
    /// Record owner or class authority for permissioned classes
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Record account associated with the tokenized record
    pub record: &'b solana_account_info::AccountInfo<'a>,
    /// Mint account for the tokenized record
    pub mint: &'b solana_account_info::AccountInfo<'a>,
    /// Class account of the record
    pub class: &'b solana_account_info::AccountInfo<'a>,
    /// Group account for the tokenized record
    pub group: &'b solana_account_info::AccountInfo<'a>,
    /// Token Account for the tokenized record
    pub token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Associated Token Program used to create our token
    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token2022 Program used to create our token
    pub token2022: &'b solana_account_info::AccountInfo<'a>,
    /// System Program used to create our token
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> MintTokenizedRecordCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: MintTokenizedRecordCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            owner: accounts.owner,
            payer: accounts.payer,
            authority: accounts.authority,
            record: accounts.record,
            mint: accounts.mint,
            class: accounts.class,
            group: accounts.group,
            token_account: accounts.token_account,
            associated_token_program: accounts.associated_token_program,
            token2022: accounts.token2022,
            system_program: accounts.system_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(11 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.owner.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.record.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.mint.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.class.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.group.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token2022.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&MintTokenizedRecordInstructionData::new()).unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(12 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.owner.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.record.clone());
        account_infos.push(self.mint.clone());
        account_infos.push(self.class.clone());
        account_infos.push(self.group.clone());
        account_infos.push(self.token_account.clone());
        account_infos.push(self.associated_token_program.clone());
        account_infos.push(self.token2022.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `MintTokenizedRecord` via CPI.
///
/// ### Accounts:
///
///   0. `[]` owner
///   1. `[writable, signer]` payer
///   2. `[signer]` authority
///   3. `[writable]` record
///   4. `[writable]` mint
///   5. `[]` class
///   6. `[writable]` group
///   7. `[writable]` token_account
///   8. `[]` associated_token_program
///   9. `[]` token2022
///   10. `[]` system_program
#[derive(Clone, Debug)]
pub struct MintTokenizedRecordCpiBuilder<'a, 'b> {
    instruction: Box<MintTokenizedRecordCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> MintTokenizedRecordCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(MintTokenizedRecordCpiBuilderInstruction {
            __program: program,
            owner: None,
            payer: None,
            authority: None,
            record: None,
            mint: None,
            class: None,
            group: None,
            token_account: None,
            associated_token_program: None,
            token2022: None,
            system_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Record owner
    #[inline(always)]
    pub fn owner(&mut self, owner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.owner = Some(owner);
        self
    }
    /// Account that will pay for the mint account
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    /// Record owner or class authority for permissioned classes
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Record account associated with the tokenized record
    #[inline(always)]
    pub fn record(&mut self, record: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.record = Some(record);
        self
    }
    /// Mint account for the tokenized record
    #[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.mint = Some(mint);
        self
    }
    /// Class account of the record
    #[inline(always)]
    pub fn class(&mut self, class: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.class = Some(class);
        self
    }
    /// Group account for the tokenized record
    #[inline(always)]
    pub fn group(&mut self, group: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.group = Some(group);
        self
    }
    /// Token Account for the tokenized record
    #[inline(always)]
    pub fn token_account(
        &mut self,
        token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_account = Some(token_account);
        self
    }
    /// Associated Token Program used to create our token
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.associated_token_program = Some(associated_token_program);
        self
    }
    /// Token2022 Program used to create our token
    #[inline(always)]
    pub fn token2022(&mut self, token2022: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.token2022 = Some(token2022);
        self
    }
    /// System Program used to create our token
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let instruction = MintTokenizedRecordCpi {
            __program: self.instruction.__program,

            owner: self.instruction.owner.expect("owner is not set"),

            payer: self.instruction.payer.expect("payer is not set"),

            authority: self.instruction.authority.expect("authority is not set"),

            record: self.instruction.record.expect("record is not set"),

            mint: self.instruction.mint.expect("mint is not set"),

            class: self.instruction.class.expect("class is not set"),

            group: self.instruction.group.expect("group is not set"),

            token_account: self
                .instruction
                .token_account
                .expect("token_account is not set"),

            associated_token_program: self
                .instruction
                .associated_token_program
                .expect("associated_token_program is not set"),

            token2022: self.instruction.token2022.expect("token2022 is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct MintTokenizedRecordCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    owner: Option<&'b solana_account_info::AccountInfo<'a>>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    record: Option<&'b solana_account_info::AccountInfo<'a>>,
    mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    class: Option<&'b solana_account_info::AccountInfo<'a>>,
    group: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token2022: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
