//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#create_class;
pub(crate) mod r#create_record;
pub(crate) mod r#create_record_authority_delegate;
pub(crate) mod r#delete_record;
pub(crate) mod r#delete_record_authority_delegate;
pub(crate) mod r#freeze_class;
pub(crate) mod r#freeze_record;
pub(crate) mod r#mint_record_token;
pub(crate) mod r#transfer_record;
pub(crate) mod r#update_class_metadata;
pub(crate) mod r#update_record;
pub(crate) mod r#update_record_authority_delegate;

pub use self::r#create_class::*;
pub use self::r#create_record::*;
pub use self::r#create_record_authority_delegate::*;
pub use self::r#delete_record::*;
pub use self::r#delete_record_authority_delegate::*;
pub use self::r#freeze_class::*;
pub use self::r#freeze_record::*;
pub use self::r#mint_record_token::*;
pub use self::r#transfer_record::*;
pub use self::r#update_class_metadata::*;
pub use self::r#update_record::*;
pub use self::r#update_record_authority_delegate::*;
