//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

/// Accounts.
#[derive(Debug)]
pub struct TransferTokenizedRecord {
    /// Record owner or class authority for permissioned classes
    pub authority: solana_pubkey::Pubkey,
    /// Mint account for the tokenized record
    pub mint: solana_pubkey::Pubkey,
    /// Token Account for the tokenized record
    pub token_account: solana_pubkey::Pubkey,
    /// New Token Account for the tokenized record
    pub new_token_account: solana_pubkey::Pubkey,
    /// Record account associated with the tokenized record
    pub record: solana_pubkey::Pubkey,
    /// Token2022 Program used to freeze/unfreeze the tokenized record
    pub token2022: solana_pubkey::Pubkey,
    /// Class account of the record
    pub class: Option<solana_pubkey::Pubkey>,
}

impl TransferTokenizedRecord {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(7 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.new_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.record,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token2022,
            false,
        ));
        if let Some(class) = self.class {
            accounts.push(solana_instruction::AccountMeta::new_readonly(class, false));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::SOLANA_RECORD_SERVICE_ID,
                false,
            ));
        }
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&TransferTokenizedRecordInstructionData::new()).unwrap();

        solana_instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TransferTokenizedRecordInstructionData {
    discriminator: u8,
}

impl TransferTokenizedRecordInstructionData {
    pub fn new() -> Self {
        Self { discriminator: 10 }
    }
}

impl Default for TransferTokenizedRecordInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `TransferTokenizedRecord`.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[]` mint
///   2. `[writable]` token_account
///   3. `[writable]` new_token_account
///   4. `[]` record
///   5. `[optional]` token2022 (default to `TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb`)
///   6. `[optional]` class
#[derive(Clone, Debug, Default)]
pub struct TransferTokenizedRecordBuilder {
    authority: Option<solana_pubkey::Pubkey>,
    mint: Option<solana_pubkey::Pubkey>,
    token_account: Option<solana_pubkey::Pubkey>,
    new_token_account: Option<solana_pubkey::Pubkey>,
    record: Option<solana_pubkey::Pubkey>,
    token2022: Option<solana_pubkey::Pubkey>,
    class: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl TransferTokenizedRecordBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Record owner or class authority for permissioned classes
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Mint account for the tokenized record
    #[inline(always)]
    pub fn mint(&mut self, mint: solana_pubkey::Pubkey) -> &mut Self {
        self.mint = Some(mint);
        self
    }
    /// Token Account for the tokenized record
    #[inline(always)]
    pub fn token_account(&mut self, token_account: solana_pubkey::Pubkey) -> &mut Self {
        self.token_account = Some(token_account);
        self
    }
    /// New Token Account for the tokenized record
    #[inline(always)]
    pub fn new_token_account(&mut self, new_token_account: solana_pubkey::Pubkey) -> &mut Self {
        self.new_token_account = Some(new_token_account);
        self
    }
    /// Record account associated with the tokenized record
    #[inline(always)]
    pub fn record(&mut self, record: solana_pubkey::Pubkey) -> &mut Self {
        self.record = Some(record);
        self
    }
    /// `[optional account, default to 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb']`
    /// Token2022 Program used to freeze/unfreeze the tokenized record
    #[inline(always)]
    pub fn token2022(&mut self, token2022: solana_pubkey::Pubkey) -> &mut Self {
        self.token2022 = Some(token2022);
        self
    }
    /// `[optional account]`
    /// Class account of the record
    #[inline(always)]
    pub fn class(&mut self, class: Option<solana_pubkey::Pubkey>) -> &mut Self {
        self.class = class;
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = TransferTokenizedRecord {
            authority: self.authority.expect("authority is not set"),
            mint: self.mint.expect("mint is not set"),
            token_account: self.token_account.expect("token_account is not set"),
            new_token_account: self
                .new_token_account
                .expect("new_token_account is not set"),
            record: self.record.expect("record is not set"),
            token2022: self.token2022.unwrap_or(solana_pubkey::pubkey!(
                "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
            )),
            class: self.class,
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `transfer_tokenized_record` CPI accounts.
pub struct TransferTokenizedRecordCpiAccounts<'a, 'b> {
    /// Record owner or class authority for permissioned classes
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Mint account for the tokenized record
    pub mint: &'b solana_account_info::AccountInfo<'a>,
    /// Token Account for the tokenized record
    pub token_account: &'b solana_account_info::AccountInfo<'a>,
    /// New Token Account for the tokenized record
    pub new_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Record account associated with the tokenized record
    pub record: &'b solana_account_info::AccountInfo<'a>,
    /// Token2022 Program used to freeze/unfreeze the tokenized record
    pub token2022: &'b solana_account_info::AccountInfo<'a>,
    /// Class account of the record
    pub class: Option<&'b solana_account_info::AccountInfo<'a>>,
}

/// `transfer_tokenized_record` CPI instruction.
pub struct TransferTokenizedRecordCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Record owner or class authority for permissioned classes
    pub authority: &'b solana_account_info::AccountInfo<'a>,
    /// Mint account for the tokenized record
    pub mint: &'b solana_account_info::AccountInfo<'a>,
    /// Token Account for the tokenized record
    pub token_account: &'b solana_account_info::AccountInfo<'a>,
    /// New Token Account for the tokenized record
    pub new_token_account: &'b solana_account_info::AccountInfo<'a>,
    /// Record account associated with the tokenized record
    pub record: &'b solana_account_info::AccountInfo<'a>,
    /// Token2022 Program used to freeze/unfreeze the tokenized record
    pub token2022: &'b solana_account_info::AccountInfo<'a>,
    /// Class account of the record
    pub class: Option<&'b solana_account_info::AccountInfo<'a>>,
}

impl<'a, 'b> TransferTokenizedRecordCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: TransferTokenizedRecordCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            mint: accounts.mint,
            token_account: accounts.token_account,
            new_token_account: accounts.new_token_account,
            record: accounts.record,
            token2022: accounts.token2022,
            class: accounts.class,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(7 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.new_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.record.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token2022.key,
            false,
        ));
        if let Some(class) = self.class {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                *class.key, false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::SOLANA_RECORD_SERVICE_ID,
                false,
            ));
        }
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&TransferTokenizedRecordInstructionData::new()).unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(8 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.mint.clone());
        account_infos.push(self.token_account.clone());
        account_infos.push(self.new_token_account.clone());
        account_infos.push(self.record.clone());
        account_infos.push(self.token2022.clone());
        if let Some(class) = self.class {
            account_infos.push(class.clone());
        }
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `TransferTokenizedRecord` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` authority
///   1. `[]` mint
///   2. `[writable]` token_account
///   3. `[writable]` new_token_account
///   4. `[]` record
///   5. `[]` token2022
///   6. `[optional]` class
#[derive(Clone, Debug)]
pub struct TransferTokenizedRecordCpiBuilder<'a, 'b> {
    instruction: Box<TransferTokenizedRecordCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> TransferTokenizedRecordCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(TransferTokenizedRecordCpiBuilderInstruction {
            __program: program,
            authority: None,
            mint: None,
            token_account: None,
            new_token_account: None,
            record: None,
            token2022: None,
            class: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Record owner or class authority for permissioned classes
    #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Mint account for the tokenized record
    #[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.mint = Some(mint);
        self
    }
    /// Token Account for the tokenized record
    #[inline(always)]
    pub fn token_account(
        &mut self,
        token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_account = Some(token_account);
        self
    }
    /// New Token Account for the tokenized record
    #[inline(always)]
    pub fn new_token_account(
        &mut self,
        new_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.new_token_account = Some(new_token_account);
        self
    }
    /// Record account associated with the tokenized record
    #[inline(always)]
    pub fn record(&mut self, record: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.record = Some(record);
        self
    }
    /// Token2022 Program used to freeze/unfreeze the tokenized record
    #[inline(always)]
    pub fn token2022(&mut self, token2022: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.token2022 = Some(token2022);
        self
    }
    /// `[optional account]`
    /// Class account of the record
    #[inline(always)]
    pub fn class(&mut self, class: Option<&'b solana_account_info::AccountInfo<'a>>) -> &mut Self {
        self.instruction.class = class;
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let instruction = TransferTokenizedRecordCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            mint: self.instruction.mint.expect("mint is not set"),

            token_account: self
                .instruction
                .token_account
                .expect("token_account is not set"),

            new_token_account: self
                .instruction
                .new_token_account
                .expect("new_token_account is not set"),

            record: self.instruction.record.expect("record is not set"),

            token2022: self.instruction.token2022.expect("token2022 is not set"),

            class: self.instruction.class,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct TransferTokenizedRecordCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    new_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    record: Option<&'b solana_account_info::AccountInfo<'a>>,
    token2022: Option<&'b solana_account_info::AccountInfo<'a>>,
    class: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
