//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_program::pubkey::Pubkey;

/// Accounts.
#[derive(Debug)]
pub struct UpdateRecordAuthorityDelegate {
    /// Authority used to create a delegate
    pub authority: solana_program::pubkey::Pubkey,
    /// Record account to create delegate for
    pub record: solana_program::pubkey::Pubkey,
    /// Delegate for record account
    pub delegate: solana_program::pubkey::Pubkey,
}

impl UpdateRecordAuthorityDelegate {
    pub fn instruction(
        &self,
        args: UpdateRecordAuthorityDelegateInstructionArgs,
    ) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: UpdateRecordAuthorityDelegateInstructionArgs,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.authority,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.record,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.delegate,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&UpdateRecordAuthorityDelegateInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_program::instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateRecordAuthorityDelegateInstructionData {
    discriminator: u8,
}

impl UpdateRecordAuthorityDelegateInstructionData {
    pub fn new() -> Self {
        Self { discriminator: 9 }
    }
}

impl Default for UpdateRecordAuthorityDelegateInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateRecordAuthorityDelegateInstructionArgs {
    pub update_authority: Pubkey,
    pub freeze_authority: Pubkey,
    pub transfer_authority: Pubkey,
    pub burn_authority: Pubkey,
    pub authority_program: Pubkey,
}

/// Instruction builder for `UpdateRecordAuthorityDelegate`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` record
///   2. `[writable]` delegate
#[derive(Clone, Debug, Default)]
pub struct UpdateRecordAuthorityDelegateBuilder {
    authority: Option<solana_program::pubkey::Pubkey>,
    record: Option<solana_program::pubkey::Pubkey>,
    delegate: Option<solana_program::pubkey::Pubkey>,
    update_authority: Option<Pubkey>,
    freeze_authority: Option<Pubkey>,
    transfer_authority: Option<Pubkey>,
    burn_authority: Option<Pubkey>,
    authority_program: Option<Pubkey>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl UpdateRecordAuthorityDelegateBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Authority used to create a delegate
    #[inline(always)]
    pub fn authority(&mut self, authority: solana_program::pubkey::Pubkey) -> &mut Self {
        self.authority = Some(authority);
        self
    }
    /// Record account to create delegate for
    #[inline(always)]
    pub fn record(&mut self, record: solana_program::pubkey::Pubkey) -> &mut Self {
        self.record = Some(record);
        self
    }
    /// Delegate for record account
    #[inline(always)]
    pub fn delegate(&mut self, delegate: solana_program::pubkey::Pubkey) -> &mut Self {
        self.delegate = Some(delegate);
        self
    }
    #[inline(always)]
    pub fn update_authority(&mut self, update_authority: Pubkey) -> &mut Self {
        self.update_authority = Some(update_authority);
        self
    }
    #[inline(always)]
    pub fn freeze_authority(&mut self, freeze_authority: Pubkey) -> &mut Self {
        self.freeze_authority = Some(freeze_authority);
        self
    }
    #[inline(always)]
    pub fn transfer_authority(&mut self, transfer_authority: Pubkey) -> &mut Self {
        self.transfer_authority = Some(transfer_authority);
        self
    }
    #[inline(always)]
    pub fn burn_authority(&mut self, burn_authority: Pubkey) -> &mut Self {
        self.burn_authority = Some(burn_authority);
        self
    }
    #[inline(always)]
    pub fn authority_program(&mut self, authority_program: Pubkey) -> &mut Self {
        self.authority_program = Some(authority_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = UpdateRecordAuthorityDelegate {
            authority: self.authority.expect("authority is not set"),
            record: self.record.expect("record is not set"),
            delegate: self.delegate.expect("delegate is not set"),
        };
        let args = UpdateRecordAuthorityDelegateInstructionArgs {
            update_authority: self
                .update_authority
                .clone()
                .expect("update_authority is not set"),
            freeze_authority: self
                .freeze_authority
                .clone()
                .expect("freeze_authority is not set"),
            transfer_authority: self
                .transfer_authority
                .clone()
                .expect("transfer_authority is not set"),
            burn_authority: self
                .burn_authority
                .clone()
                .expect("burn_authority is not set"),
            authority_program: self
                .authority_program
                .clone()
                .expect("authority_program is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `update_record_authority_delegate` CPI accounts.
pub struct UpdateRecordAuthorityDelegateCpiAccounts<'a, 'b> {
    /// Authority used to create a delegate
    pub authority: &'b solana_program::account_info::AccountInfo<'a>,
    /// Record account to create delegate for
    pub record: &'b solana_program::account_info::AccountInfo<'a>,
    /// Delegate for record account
    pub delegate: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `update_record_authority_delegate` CPI instruction.
pub struct UpdateRecordAuthorityDelegateCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,
    /// Authority used to create a delegate
    pub authority: &'b solana_program::account_info::AccountInfo<'a>,
    /// Record account to create delegate for
    pub record: &'b solana_program::account_info::AccountInfo<'a>,
    /// Delegate for record account
    pub delegate: &'b solana_program::account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: UpdateRecordAuthorityDelegateInstructionArgs,
}

impl<'a, 'b> UpdateRecordAuthorityDelegateCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: UpdateRecordAuthorityDelegateCpiAccounts<'a, 'b>,
        args: UpdateRecordAuthorityDelegateInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            authority: accounts.authority,
            record: accounts.record,
            delegate: accounts.delegate,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.authority.key,
            true,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.record.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.delegate.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&UpdateRecordAuthorityDelegateInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::SOLANA_RECORD_SERVICE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.authority.clone());
        account_infos.push(self.record.clone());
        account_infos.push(self.delegate.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `UpdateRecordAuthorityDelegate` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` authority
///   1. `[writable]` record
///   2. `[writable]` delegate
#[derive(Clone, Debug)]
pub struct UpdateRecordAuthorityDelegateCpiBuilder<'a, 'b> {
    instruction: Box<UpdateRecordAuthorityDelegateCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdateRecordAuthorityDelegateCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(UpdateRecordAuthorityDelegateCpiBuilderInstruction {
            __program: program,
            authority: None,
            record: None,
            delegate: None,
            update_authority: None,
            freeze_authority: None,
            transfer_authority: None,
            burn_authority: None,
            authority_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Authority used to create a delegate
    #[inline(always)]
    pub fn authority(
        &mut self,
        authority: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.authority = Some(authority);
        self
    }
    /// Record account to create delegate for
    #[inline(always)]
    pub fn record(
        &mut self,
        record: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.record = Some(record);
        self
    }
    /// Delegate for record account
    #[inline(always)]
    pub fn delegate(
        &mut self,
        delegate: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.delegate = Some(delegate);
        self
    }
    #[inline(always)]
    pub fn update_authority(&mut self, update_authority: Pubkey) -> &mut Self {
        self.instruction.update_authority = Some(update_authority);
        self
    }
    #[inline(always)]
    pub fn freeze_authority(&mut self, freeze_authority: Pubkey) -> &mut Self {
        self.instruction.freeze_authority = Some(freeze_authority);
        self
    }
    #[inline(always)]
    pub fn transfer_authority(&mut self, transfer_authority: Pubkey) -> &mut Self {
        self.instruction.transfer_authority = Some(transfer_authority);
        self
    }
    #[inline(always)]
    pub fn burn_authority(&mut self, burn_authority: Pubkey) -> &mut Self {
        self.instruction.burn_authority = Some(burn_authority);
        self
    }
    #[inline(always)]
    pub fn authority_program(&mut self, authority_program: Pubkey) -> &mut Self {
        self.instruction.authority_program = Some(authority_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let args = UpdateRecordAuthorityDelegateInstructionArgs {
            update_authority: self
                .instruction
                .update_authority
                .clone()
                .expect("update_authority is not set"),
            freeze_authority: self
                .instruction
                .freeze_authority
                .clone()
                .expect("freeze_authority is not set"),
            transfer_authority: self
                .instruction
                .transfer_authority
                .clone()
                .expect("transfer_authority is not set"),
            burn_authority: self
                .instruction
                .burn_authority
                .clone()
                .expect("burn_authority is not set"),
            authority_program: self
                .instruction
                .authority_program
                .clone()
                .expect("authority_program is not set"),
        };
        let instruction = UpdateRecordAuthorityDelegateCpi {
            __program: self.instruction.__program,

            authority: self.instruction.authority.expect("authority is not set"),

            record: self.instruction.record.expect("record is not set"),

            delegate: self.instruction.delegate.expect("delegate is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct UpdateRecordAuthorityDelegateCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    record: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    delegate: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    update_authority: Option<Pubkey>,
    freeze_authority: Option<Pubkey>,
    transfer_authority: Option<Pubkey>,
    burn_authority: Option<Pubkey>,
    authority_program: Option<Pubkey>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
