[package]
name = "solana-record-service"
version = { workspace = true }
edition = { workspace = true }

[lib]
name = "srs"
crate-type = ["lib", "cdylib"]

[build-dependencies]
codama = { workspace = true }
serde_json = { workspace = true }

[dependencies]
codama = { workspace = true }
pinocchio = { workspace = true }
pinocchio-associated-token-account = { workspace = true }
pinocchio-system = { workspace = true }
pinocchio-token-2022 = { workspace = true }
solana-address = { workspace = true }

[lints]
workspace = true
