[package]
name = "solana-record-service"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = "0.8.3"
pinocchio-system = "0.2.3"

[dev-dependencies]
solana-record-service-sdk = { workspace = true }
mollusk-svm = "0.1.4"
solana-sdk = "2.2.0"
solana-program = "2.2.0"
kaigan = ">=0.2.6"
borsh = "^0.10"
hex = "0.4.3"