//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#class;
pub(crate) mod r#record;
pub(crate) mod r#record_delegate;

pub use self::r#class::*;
pub use self::r#record::*;
pub use self::r#record_delegate::*;
